tap "homebrew/bundle"
tap "homebrew/services"
brew "ansible"
brew "argocd"
brew "deno"
brew "dive"
brew "doctl"
brew "fnm"
brew "gh"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "go"
brew "goaccess"
brew "helm"
brew "httpie"
brew "hub"
brew "jc"
brew "jq"
brew "kubebuilder"
brew "k9s"
brew "kubernetes-cli"
brew "kubectx"
brew "kubeseal"
brew "kustomize"
brew "libfido2"
brew "mas"
brew "nmap"
brew "openssh"
brew "operator-sdk"
brew "pinentry-mac"
brew "pv"
brew "python@3.9"
brew "redis"
brew "rustup"
brew "stern"
brew "terraform"
brew "tree"
brew "vault"
brew "wget"
brew "woff2"
brew "ykman"
brew "yq"
cask "1password"
cask "docker"
cask "firefox"
cask "focusrite-control-2"
cask "monitorcontrol"
cask "nova"
cask "sf-symbols"
cask "sketch"
cask "slack"
cask "transmit"
cask "visual-studio-code"
cask "zoom"
mas "Boop", id: 1518425043
mas "BrowserNow", id: 1633886387
mas "Color Picker", id: 1545870783
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Prompt", id: 1594420480
mas "Reeder", id: 1529448980
mas "Sleeve", id: 1606145041
mas "Things", id: 904280696
mas "Xcode", id: 497799835
mas "Yoath", id: 1660931205
mas "Yubico Authenticator", id: 1497506650
vscode "amandeepmittal.pug"
vscode "christian-kohler.npm-intellisense"
vscode "dbaeumer.vscode-eslint"
vscode "denoland.vscode-deno"
vscode "dracula-theme.theme-dracula"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "GitHub.github-vscode-theme"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "GraphQL.vscode-graphql-syntax"
vscode "Gruntfuggly.todo-tree"
vscode "hashicorp.hcl"
vscode "hashicorp.terraform"
vscode "korekontrol.saltstack"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.hexeditor"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.vscode-serial-monitor"
vscode "ms-vsliveshare.vsliveshare"
vscode "octref.vetur"
vscode "PKief.material-icon-theme"
vscode "platformio.platformio-ide"
vscode "Prisma.prisma"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "ronnidc.nunjucks"
vscode "syler.sass-indented"
vscode "Vue.volar"
vscode "Vue.vscode-typescript-vue-plugin"
vscode "william-voyek.vscode-nginx"
